### ISSUE TITLE
Changing the color of the acejump tooltip

### ISSUE THREAD

**Issue by marpe** [whunmr/emacsIDEAs#10]
Is there any way to change the color of the acejump tooltip? Right now I have it bright red on white background which is kind of hard to see. Would be great if there was some way to add a bit of padding as well.

**Comment by whunmr** [comment]
@marpe , Thanks for the suggestions, the options is added in the Preferences --> Other Settings --> emacsIDEAs.

Please update to version 1.3.9 to get the new feature.
