### ISSUE TITLE
Featuer request: Add an option to deselect copied/moved texts automatically

### ISSUE THREAD

**Issue by Centaur** [whunmr/emacsIDEAs#11]
Currently the copied/moved texts remain selected, I have to stroke another ESC key to deselect to continue editing.

**Comment by whunmr** [comment]
the moved texts are selected, so we can issue Format command directly on the recently moved texts.

So I'd like to keep it selected.

**Comment by Centaur** [comment]
Yes. Some need it to be selected, but others need it to be unselected. That is why  I suggest making it an configurable option.

**Comment by whunmr** [comment]
Make sense.  Will support when I have time to enhance this plugin.   Mean while any pull request will be appreciated.
Get Outlook for iOS




On Wed, May 18, 2016 at 12:54 AM -0700, "oldpig" <notifications@github.com> wrote:












Yes. Some need it to be selected, but others need it to be unselected. That is why  I suggest making it an configurable option.

**Comment by whunmr** [comment]
@Centaur,  Thanks for the suggestions, the options is added in the Preferences --> Other Settings --> emacsIDEAs.

Please update to version 1.3.9 to get the new feature.
