### ISSUE TITLE
Feature request: Jump/Copy/Replace from/to the splitted pane

### ISSUE THREAD

**Issue by Centaur** [whunmr/emacsIDEAs#13]
One of idea's cool features is splitting the edit window horizontally/vertically. 
![Example](https://www.jetbrains.com/help/img/idea/splitEditorTab.png)
It would be very nice if emacsIDEA can Jump/Copy/Replace text from/to the splitted pane(s) as well.

**Comment by whunmr** [comment]
Good idea, will put this feature request in backlog.  
meanwhile, pull request is always welcome.

**Comment by whunmr** [comment]
@Centaur checkout new release 1.4.2.   Thanks for your ideas.

**Comment by Centaur** [comment]
Wow, Godspeed!
