### ISSUE TITLE
overlay and markers in splitted panes not get cleared after jump

### ISSUE THREAD

**Issue by Centaur** [whunmr/emacsIDEAs#14]
![2016-08-31 10 29 48](https://cloud.githubusercontent.com/assets/265524/18132735/8205c4c8-6fca-11e6-88d1-07b26bfb9e34.png)

reproduce:
1. in the above pane, move cursor to end of line 18
2. `c-l` `[space]`  `a` jump to end of line 19 as expected. But the splitted pane below does not get cleaned up.

**Comment by whunmr** [comment]
hi @Centaur , thanks for let us know the issue, please upgrade the plugin to 1.4.3 for fix.

the fix was test on:
> IntelliJ IDEA 2016.2.2
> Build #IC-162.1628.40, built on August 16, 2016
> JRE: 1.8.0_76-release-b216 x86_64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
