### ISSUE TITLE
Installed plugin, emacsIDEAs doesn't seem to be responding to any of its control commands

### ISSUE THREAD

**Issue by jmcmichael** [whunmr/emacsIDEAs#16]
Hi, this looks like SUCH a great plugin and I really want to use it in my work, but I've tried again to install it (tried back in 2013 with similar results), and I can't tell that it does anything for me.

It doesn't appear like C-c has any effect - if I hit C-c a, IntelliJ just inserts an 'a', if I hit C-L [space], it just inserts a space. It appears that emacsIDEAs isn't responding at all to its initiation commands.

Am I missing any post-install instructions? I'm using a custom keymap that is a slight variation to the built-in Emacs keymap - do I need to use the built in keymap? Do you have any suggestions as how to proceed figuring out what the problem is?

**Comment by whunmr** [comment]
hi @jmcmichael, Are you using in Windows? 

if Yes, 

firstly, please down the windows version:   https://raw.githubusercontent.com/whunmr/emacsIDEAs/master/emacsideas-windows.jar

secondly, by default Ctrl-c is mapping to COPY on windows, so there is a conflict. to fix this, remapping COPY to another shortcut key is needed.

**Comment by whunmr** [comment]
hi @jmcmichael, any update?

**Comment by whunmr** [comment]
@jmcmichael,  I will close this issue now. please reopen it if you still got problems when using this plugin.

**Comment by xin-jin** [comment]
Hey @whunmr , I am having the same issue. None of prefix keys work for me. I am on Ubuntu 16.04.
