### ISSUE TITLE
How to map emacsIDEAs actions via .ideavimrc?

### ISSUE THREAD

**Issue by ascenator** [whunmr/emacsIDEAs#17]
I would like to map keys in my .ideavimrc instead of the IDEs keymap. How can I do so?

This, for example, was one possible mapping that I've already tried:
```
map <space>c :action AceJumpChar<CR>
```
Unfortunately, it did not work.

**Comment by whunmr** [comment]
@ascenator thanks for the suggestions. I haven't tried .ideavimrc, will try this way later. 

In the mean time,  you can try other id's of the actions, such as emacsIDEAs.AceJump or org.hunmr.acejump.AceJumpCharAction. please leave comments if it works, Thanks!


All the action description is in https://github.com/whunmr/emacsIDEAs/blob/master/resources/META-INF/plugin.xml

<action id="emacsIDEAs.AceJump" class="org.hunmr.acejump.AceJumpCharAction" text="AceJumpChar" description="AceJumpChar" >
        <keyboard-shortcut keymap="$default" first-keystroke="meta J" />
</action>

**Comment by ascenator** [comment]
`org.hunmr.acejump.AceJumpCharAction` is not working for me, but `emacsIDEAs.AceJump` does work. I will try more commands and update :)

**Comment by whunmr** [comment]
@ascenator, cool.   

Would be great if you can share your .ideavimrc mapping for this plugin.
Thanks in advance.
