### ISSUE TITLE
Feature Request: enter "esc" to escape from jumping mode.

### ISSUE THREAD

**Issue by xdidi3r** [whunmr/emacsIDEAs#19]
When I accidentally press the shortcut key, i was forced to type some letters to escape from the jumping mode and jump to where I do not want to go. I hope that i can press "esc" instead of typing some letters.
Thanks for your great job. This Plugin becomes an indispensable tool for me. So i hope it gets better.

**Comment by whunmr** [comment]
hi @xdidi3r, Thanks for using this plugin.

I think we already have this feature.

Which application are you using, IntelliJ IDEA or Clion or PyCharm?  
And which version of this plugin are you using?

**Comment by xdidi3r** [comment]
Well, I found that the "IdeaVim" will destroy this feature.

**Comment by xdidi3r** [comment]
When I use acejump in visual mode, the "esc" not work for emacsideas.

**Comment by whunmr** [comment]
try the latest new version: 1.4.6

--- fix 'esc' key can not exit jump mode if ideaVim is activated and in visual mode. 
--- To exit jump mode now we can press, ESC, SEMICOLON, or SPACE.

**Comment by xdidi3r** [comment]
In this version, I can press SEMICOLON or SPACE to exit jump mode.  But ESC still does not work.

**Comment by whunmr** [comment]
Yes, the SEMICOLON and SPACE is the fix.
Also i find that SPACE is more easy to press than ESC.  :)

**Comment by xdidi3r** [comment]
I prefer the SPACE too. Thanks!
