### ISSUE TITLE
Collaboration with AceJump

### ISSUE THREAD

**Issue by breandan** [whunmr/emacsIDEAs#23]
[AceJump](https://github.com/johnlindquist/AceJump) is the most popular [EasyMotion](https://github.com/easymotion/vim-easymotion)/[ace-jump](https://github.com/winterTTr/ace-jump-mode) implementation for the IntelliJ Platform, with [thousands](https://plugins.jetbrains.com/dashboard/statistics/downloads/byTime?pluginId=7086) of active users. It solves some weird graphical bugs, adds some neat features for search and navigation, and is maintained by @johnlindquist and myself. For emacs users, it would be nice to offer AceJump as a keybinding (like we do [in ideavim](https://github.com/johnlindquist/AceJump#configuring)), and we would be happy to have you as a collaborator (possibly porting some of your features to AceJump, as it looks like you've implemented some [interesting actions](https://github.com/whunmr/emacsIDEAs/tree/master/src/org/hunmr/acejump)), and I could help migrating your code to [Kotlin](https://kotlinlang.org/) and [Gradle](https://github.com/jetbrains/gradle-intellij-plugin). I believe both plugins would benefit from this effort. Would you be interested in such a collaboration?

**Comment by whunmr** [comment]
sounds great 👍,  glad to know you guys.  
add me as collaborator please.

**Comment by breandan** [comment]
Awesome! @johnlindquist can you add @whunmr as a collaborator to the AceJump repo?

**Comment by breandan** [comment]
@whunmr You should have access now. Can you add me as a collaborator to this repo? Thanks!
