### ISSUE TITLE
为什么ESC无法退出emacsIDEAs

### ISSUE THREAD

**Issue by Ailen1988** [whunmr/emacsIDEAs#26]
谢谢whunmr 提供的插件, 最近在研究, 碰到了一些问题.
为什么ESC无法退出emacsIDEAs, 只能再次点击进行退出, 有什么方式可以解决的么?

**Comment by whunmr** [comment]
你在哪个工具？IntelliJ IDEA?   哪个版本中使用？

我在下面版本上可以用ESC退出emacsIDEAs,  也可以用空格键退出。  
IntelliJ IDEA 2017.1.3
Build #IC-171.4424.56, built on May 13, 2017

你试试空格键在你那里能否退出？

**Comment by Ailen1988** [comment]
用的是phpstrom, 涉及版本phpstorm2016.2 , phpstorm2016.3, phpstorm2017.2.
这三个版本中, 我使用的时候, 都是无法用esc退出的.

**刚才试了一下空格键, 确实是可以退出的**

-----

=.= 
应该是我对emacsIDEAs理解有问题, 我操作的方式, 通常都是这样的:
e,g:
当我要跳转的时候, 首先敲击
`Meta + j`
这个时候界面是没有反应的, 只有在敲击了一次空格以后才会有用,
而且,  我发现在有时候使用的时候, 敲击不同次数的空格, 会有不同的效果...

以上, 是我对空格操作的困惑.

--------

最后, 谢谢你制作的插件, 很*好用*!

**Comment by Ailen1988** [comment]
刚看了 [#19](https://github.com/whunmr/emacsIDEAs/issues/19),
在这里补充一句, 我也是使用的ideavim....
