### ISSUE TITLE
移植到Visual Studio Code

### ISSUE THREAD

**Issue by oncealong** [whunmr/emacsIDEAs#29]
这么好用的插件，大神有意向移植到Visual Studio Code么？毕竟很多前端都不用IDE的

**Comment by vhunmr** [comment]
可以考虑，但是最近没有时间做这件事。 同时如果你有意向移植的话， 我可以提供支持。

**Comment by oncealong** [comment]
暂时醉心于Android，还没有意向和能力做这个移植。
