### ISSUE TITLE
AceJump: Show two-letter combos up front

### ISSUE THREAD

**Issue by jmdodge** [whunmr/emacsIDEAs#3]
Just a little feature request - when I'm using AceJump, the nearer jumps take only one keystroke, but when there are many possibilities the further jumps take two keystrokes.
I think it would be much easier to get to these further jumps if their two-key combination was shown on the screen right up front, but instead you have to hit the first key and then wait for the second key needed to be revealed.
It's a subtle thing, but just enough for me to feel like jumping can be slightly more cumbersome than I want and I get lazy and don't use it.  This is also how the other dedicated AceJump plugin works, but there is another bug with that plugin that prevents me from using it.

**Comment by whunmr** [comment]
@jmdodge  checkout the new version 1.3.3 which jumps more like avy-jump.  Thanks for the suggestion.

https://plugins.jetbrains.com/plugin/7163?pr=idea
https://plugins.jetbrains.com/plugin/download?pr=idea&updateId=27543

**Comment by jmdodge** [comment]
@whunmr - Awesome! I think this is a definite improvement!
