### ISSUE TITLE
Error when using any operation with copy/paste

### ISSUE THREAD

**Issue by agluszyk** [whunmr/emacsIDEAs#5]
Every operation consisting copying (for example Obtain and Replace) results in error:

8:54:53 AM NoClassDefFoundError: com/intellij/openapi/editor/impl/EditorCopyPasteHelperImpl: com/intellij/openapi/editor/impl/EditorCopyPasteHelperImpl

Im using IDEA 13.1.6 on Windows and EmacsIDEAs 1.3.2

**Comment by whunmr** [comment]
Hi @agluszyk, this is because plugin sdk api update, please
use latest version of IntelliJ idea
Or try using the old version of this plugin from plugin page 

http://plugins.jetbrains.com/plugin/?idea_ce&pluginId=7163

**Comment by whunmr** [comment]
will close the issue now, please reopen if still exists.
