### ISSUE TITLE
Marker letters alignement

### ISSUE THREAD

**Issue by agluszyk** [whunmr/emacsIDEAs#6]
When using specific fonts, without line height, I gues,  like Anonymous Pro markers are drawn lower than regular font. Markers like "j" and "i" are also ambigous due to theirs positioning in box.
![outofthebox](https://cloud.githubusercontent.com/assets/7798111/6210655/122701de-b5d2-11e4-96e7-4ddb032a06a8.png)

**Comment by whunmr** [comment]
checkout the new release.  https://plugins.jetbrains.com/plugin/?idea_ce&pluginId=7163
have made the background white block more taller.

**Comment by whunmr** [comment]
![Uploading Screen Shot 2016-08-11 at 11.46.34 PM.png…]()
