### ISSUE TITLE
what is the use of C-I C-R series

### ISSUE THREAD

**Issue by Centaur** [whunmr/emacsIDEAs#7]
These commands are identical to those in the C-I series, have I missed something important?

**Comment by whunmr** [comment]
hi @Centaur,

the C-I C-R series is keep for old users.  will be removed in future version.
it's identical to following functions:

Replace target (word | line | paragraph) with text at current caret:
C-i C-w 't' 'm' : replace target word
C-i C-s 't' 'm' : replace target string
C-i C-l 't' 'm' : replace target line
C-i C-b 't' 'm' : replace target block
C-i C-q 't' 'm' : replace target quote
C-i C-a 't' 'm' : replace target to line begining
C-i C-e 't' 'm' : replace target char to line end
C-i C-p 't' 'm' : replace target paragraph
C-i C-u 't' 'm' : replace target to paragraph beginning
C-i C-d 't' 'm' : replace target to paragraph end
