### ISSUE TITLE
Request: emacsIDEAs for CLion

### ISSUE THREAD

**Issue by ascenator** [whunmr/emacsIDEAs#8]
Is there any chance of porting this plugin to the newest IDE of jetbrains: CLion?

Would be awesome :)

**Comment by whunmr** [comment]
I'll try porting it to CLion when I got spare time, meanwhile I'd very like to accept pull request from you guys. Thanks

**Comment by whunmr** [comment]
@ascenator 
Currently this plugin can run on CLion,  I have done nothing.   

Just tested on Clion 1.1
